spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board
    username: postgres
    password: "0000"
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create